/**
 * GitHub Actionsワークフロー生成
 * 前のPRがマージされたら次のPRのdraftを解除するワークフローを生成する
 */

import { getOctokit } from "./client.js";

interface WorkflowChainItem {
  /** マージを監視するPR番号 */
  watchPRNumber: number;
  /** マージ後にdraft解除するPR番号 */
  nextPRNumber: number;
  /** ワークフロー識別用の名前 */
  name: string;
}

/**
 * チェーンPRのマージ監視ワークフローを生成する
 */
export function generateWorkflowYaml(item: WorkflowChainItem): string {
  return `# Auto-generated by prsplit - Chain PR merge watcher
# If PR #${item.watchPRNumber} is merged, mark PR #${item.nextPRNumber} as ready for review
name: "prsplit: ${item.name}"

on:
  pull_request:
    types: [closed]

jobs:
  promote-next-pr:
    if: >-
      github.event.pull_request.merged == true &&
      github.event.pull_request.number == ${item.watchPRNumber}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Mark next PR as ready for review
        uses: actions/github-script@v7
        with:
          github-token: \${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${item.nextPRNumber},
            });

            if (pr.draft) {
              await github.graphql(\`
                mutation($pullRequestId: ID!) {
                  markPullRequestReadyForReview(input: { pullRequestId: $pullRequestId }) {
                    pullRequest { isDraft }
                  }
                }
              \`, { pullRequestId: pr.node_id });

              console.log('Marked PR #${item.nextPRNumber} as ready for review');
            } else {
              console.log('PR #${item.nextPRNumber} is already ready for review');
            }
`;
}

/**
 * 最終PRがマージされたら元PRをcloseするワークフロー
 */
export function generateCloseOriginalWorkflowYaml(
  lastPRNumber: number,
  originalPRNumber: number
): string {
  return `# Auto-generated by prsplit - Auto-close original PR
# If final split PR #${lastPRNumber} is merged, close original PR #${originalPRNumber}
name: "prsplit: close original PR #${originalPRNumber}"

on:
  pull_request:
    types: [closed]

jobs:
  close-original-pr:
    if: >-
      github.event.pull_request.merged == true &&
      github.event.pull_request.number == ${lastPRNumber}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Close original PR
        uses: actions/github-script@v7
        with:
          github-token: \${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${originalPRNumber},
              state: 'closed',
            });

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${originalPRNumber},
              body: '✅ All split PRs were merged, so this original PR was closed automatically.',
            });

            console.log('Closed original PR #${originalPRNumber}');
`;
}

/**
 * ワークフローファイルをリポジトリにコミットする
 */
export async function commitWorkflows(
  owner: string,
  repo: string,
  branchName: string,
  workflows: Array<{ filename: string; content: string }>
): Promise<void> {
  const octokit = getOctokit();

  // ブランチのHEAD SHAを取得
  const { data: ref } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${branchName}`,
  });
  const baseSha = ref.object.sha;

  // Treeを構築
  const treeItems = workflows.map((wf) => ({
    path: `.github/workflows/prsplit/${wf.filename}`,
    mode: "100644" as const,
    type: "blob" as const,
    content: wf.content,
  }));

  const { data: tree } = await octokit.rest.git.createTree({
    owner,
    repo,
    base_tree: baseSha,
    tree: treeItems,
  });

  const { data: commit } = await octokit.rest.git.createCommit({
    owner,
    repo,
    message: "chore(prsplit): add chain PR workflow files",
    tree: tree.sha,
    parents: [baseSha],
  });

  await octokit.rest.git.updateRef({
    owner,
    repo,
    ref: `heads/${branchName}`,
    sha: commit.sha,
  });
}
