import { beforeEach, describe, expect, it, vi } from "vitest";

const mockOctokit = {
  rest: {
    pulls: {
      list: vi.fn(),
      update: vi.fn(),
    },
    git: {
      deleteRef: vi.fn(),
    },
  },
  paginate: {
    iterator: vi.fn(),
  },
};

vi.mock("../src/github/client.js", () => ({
  getOctokit: () => mockOctokit,
}));

import {
  closePRs,
  findDraftSplitPRsByOriginalPR,
} from "../src/github/pr.js";

type PullListItem = {
  number: number;
  title: string;
  html_url: string;
  draft: boolean;
  body: string | null;
  head: { ref: string };
};

function createIterator(
  pages: Array<{ data: PullListItem[] }>
): AsyncGenerator<{ data: PullListItem[] }, void, unknown> {
  return (async function* iterator() {
    for (const page of pages) {
      yield page;
    }
  })();
}

describe("findDraftSplitPRsByOriginalPR", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("指定した元PR由来かつdraftのprsplit生成PRだけを返す", async () => {
    const matchingBody = `text
| Original PR | #123 |
*This PR was automatically generated by [prsplit](https://github.com/prsplit/prsplit).*`;

    mockOctokit.paginate.iterator.mockReturnValue(
      createIterator([
        {
          data: [
            {
              number: 10,
              title: "[1/2] feat: one",
              html_url: "https://example.com/pr/10",
              draft: true,
              body: matchingBody,
              head: { ref: "feat/one" },
            },
            {
              number: 11,
              title: "[2/2] feat: two",
              html_url: "https://example.com/pr/11",
              draft: false,
              body: matchingBody,
              head: { ref: "feat/two" },
            },
            {
              number: 12,
              title: "wrong original",
              html_url: "https://example.com/pr/12",
              draft: true,
              body: matchingBody.replace("#123", "#999"),
              head: { ref: "feat/wrong-original" },
            },
            {
              number: 13,
              title: "missing footer",
              html_url: "https://example.com/pr/13",
              draft: true,
              body: "| Original PR | #123 |",
              head: { ref: "feat/missing-footer" },
            },
          ],
        },
        {
          data: [
            {
              number: 14,
              title: "null body",
              html_url: "https://example.com/pr/14",
              draft: true,
              body: null,
              head: { ref: "feat/null-body" },
            },
            {
              number: 15,
              title: "[extra] feat: three",
              html_url: "https://example.com/pr/15",
              draft: true,
              body: matchingBody,
              head: { ref: "feat/three" },
            },
          ],
        },
      ])
    );

    const result = await findDraftSplitPRsByOriginalPR("acme", "repo", 123);

    expect(result).toEqual([
      {
        number: 10,
        title: "[1/2] feat: one",
        htmlUrl: "https://example.com/pr/10",
        branchName: "feat/one",
      },
      {
        number: 15,
        title: "[extra] feat: three",
        htmlUrl: "https://example.com/pr/15",
        branchName: "feat/three",
      },
    ]);
    expect(mockOctokit.paginate.iterator).toHaveBeenCalledWith(
      mockOctokit.rest.pulls.list,
      { owner: "acme", repo: "repo", state: "open", per_page: 100 }
    );
  });

  it("一致するPRがない場合は空配列を返す", async () => {
    mockOctokit.paginate.iterator.mockReturnValue(
      createIterator([
        {
          data: [
            {
              number: 21,
              title: "non-draft",
              html_url: "https://example.com/pr/21",
              draft: false,
              body: "| Original PR | #123 |",
              head: { ref: "feat/non-draft" },
            },
          ],
        },
      ])
    );

    const result = await findDraftSplitPRsByOriginalPR("acme", "repo", 123);
    expect(result).toEqual([]);
  });
});

describe("closePRs", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("複数PRに対してcloseとbranch削除を実行する", async () => {
    mockOctokit.rest.pulls.update.mockResolvedValue(undefined);
    mockOctokit.rest.git.deleteRef.mockResolvedValue(undefined);

    await closePRs("acme", "repo", [
      {
        number: 100,
        title: "first",
        htmlUrl: "https://example.com/pr/100",
        branchName: "feat/first",
      },
      {
        number: 101,
        title: "second",
        htmlUrl: "https://example.com/pr/101",
        branchName: "feat/second",
      },
    ]);

    expect(mockOctokit.rest.pulls.update).toHaveBeenCalledTimes(2);
    expect(mockOctokit.rest.pulls.update).toHaveBeenNthCalledWith(1, {
      owner: "acme",
      repo: "repo",
      pull_number: 100,
      state: "closed",
    });
    expect(mockOctokit.rest.pulls.update).toHaveBeenNthCalledWith(2, {
      owner: "acme",
      repo: "repo",
      pull_number: 101,
      state: "closed",
    });

    expect(mockOctokit.rest.git.deleteRef).toHaveBeenCalledTimes(2);
    expect(mockOctokit.rest.git.deleteRef).toHaveBeenNthCalledWith(1, {
      owner: "acme",
      repo: "repo",
      ref: "heads/feat/first",
    });
    expect(mockOctokit.rest.git.deleteRef).toHaveBeenNthCalledWith(2, {
      owner: "acme",
      repo: "repo",
      ref: "heads/feat/second",
    });
  });
});
